[package]
name = "bevy_mapengine"
version = "0.1.0"
authors = ["Matthew Miller <mattdm@mattdm.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
